"""Data models for SignDocs Brasil SDK."""

from .document import (
    ConfirmDocumentRequest,
    ConfirmDocumentResponse,
    DocumentUploadResponse,
    DownloadResponse,
    PresignRequest,
    PresignResponse,
    UploadDocumentRequest,
)
from .document_group import CombinedStampResponse
from .envelope import (
    AddEnvelopeSessionRequest,
    CreateEnvelopeRequest,
    Envelope,
    EnvelopeDetail,
    EnvelopeSession,
    EnvelopeSessionSummary,
)
from .evidence import (
    EnvelopeVerificationDownloads,
    EnvelopeVerificationResponse,
    EnvelopeVerificationSigner,
    Evidence,
    EvidenceDocument,
    EvidenceSigner,
    EvidenceStep,
    VerificationDownloadItem,
    VerificationDownloads,
    VerificationDownloadsResponse,
    VerificationResponse,
    VerificationSigner,
)
from .health import HealthCheckResponse, HealthHistoryResponse, ServiceHealth
from .signing import (
    CompleteSigningDigitalSignatureResult,
    CompleteSigningRequest,
    CompleteSigningResponse,
    CompleteSigningResult,
    PrepareSigningRequest,
    PrepareSigningResponse,
)
from .step import (
    CompleteBiometricMatchRequest,
    CompleteClickRequest,
    CompleteLivenessRequest,
    CompleteOtpRequest,
    CompleteStepResponse,
    ReferenceImage,
    StartStepRequest,
    StartStepResponse,
    StepCompleteResponse,
    StepListResponse,
)
from .transaction import (
    ActionMetadata,
    CancelTransactionResponse,
    CaptureMode,
    ClickResult,
    CreateTransactionRequest,
    DigitalSignatureMetadata,
    DigitalSignatureResult,
    FinalizeResponse,
    InlineDocument,
    LivenessResult,
    MatchResult,
    OtpResult,
    Policy,
    PolicyProfile,
    Signer,
    Step,
    StepResult,
    StepStatus,
    StepType,
    Transaction,
    TransactionListParams,
    TransactionListResponse,
    TransactionPurpose,
    TransactionStatus,
)
from .user import EnrollUserRequest, EnrollUserResponse
from .webhook import (
    RegisterWebhookRequest,
    RegisterWebhookResponse,
    Webhook,
    WebhookEventType,
    WebhookPayload,
    WebhookTestResponse,
)

__all__ = [
    # Transaction
    "TransactionStatus",
    "StepType",
    "StepStatus",
    "PolicyProfile",
    "TransactionPurpose",
    "CaptureMode",
    "Policy",
    "Signer",
    "ActionMetadata",
    "DigitalSignatureMetadata",
    "InlineDocument",
    "CreateTransactionRequest",
    "LivenessResult",
    "MatchResult",
    "OtpResult",
    "ClickResult",
    "DigitalSignatureResult",
    "StepResult",
    "Step",
    "Transaction",
    "TransactionListResponse",
    "TransactionListParams",
    "CancelTransactionResponse",
    "FinalizeResponse",
    # Document
    "UploadDocumentRequest",
    "PresignRequest",
    "PresignResponse",
    "ConfirmDocumentRequest",
    "ConfirmDocumentResponse",
    "DocumentUploadResponse",
    "DownloadResponse",
    # Step
    "StartStepRequest",
    "StartStepResponse",
    "CompleteClickRequest",
    "CompleteOtpRequest",
    "CompleteLivenessRequest",
    "ReferenceImage",
    "CompleteBiometricMatchRequest",
    "CompleteStepResponse",
    "StepListResponse",
    "StepCompleteResponse",
    # Signing
    "PrepareSigningRequest",
    "PrepareSigningResponse",
    "CompleteSigningRequest",
    "CompleteSigningDigitalSignatureResult",
    "CompleteSigningResult",
    "CompleteSigningResponse",
    # Webhook
    "WebhookEventType",
    "RegisterWebhookRequest",
    "RegisterWebhookResponse",
    "Webhook",
    "WebhookPayload",
    "WebhookTestResponse",
    # Evidence
    "EvidenceSigner",
    "EvidenceDocument",
    "EvidenceStep",
    "Evidence",
    "VerificationSigner",
    "VerificationResponse",
    "VerificationDownloadItem",
    "VerificationDownloads",
    "VerificationDownloadsResponse",
    "EnvelopeVerificationSigner",
    "EnvelopeVerificationDownloads",
    "EnvelopeVerificationResponse",
    # User
    "EnrollUserRequest",
    "EnrollUserResponse",
    # Health
    "ServiceHealth",
    "HealthCheckResponse",
    "HealthHistoryResponse",
    # Document Group
    "CombinedStampResponse",
    # Envelope
    "CreateEnvelopeRequest",
    "Envelope",
    "AddEnvelopeSessionRequest",
    "EnvelopeSession",
    "EnvelopeSessionSummary",
    "EnvelopeDetail",
]
